name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers only on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install dynaconf

      - name: Get version from settings
        id: get_version
        run: |
          echo "VERSION=$(python -c 'from config.config import settings; print(settings.openapi.version)')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/strata-fit-data-val:${{ env.VERSION }}
          docker tag ghcr.io/${{ github.repository_owner }}/strata-fit-data-val:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/strata-fit-data-val:latest
  
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/strata-fit-data-val:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/strata-fit-data-val:latest

